### ISSUE TITLE
angular/no-digest and angular/typecheck-regexp was not found

### ISSUE THREAD

**Issue by ankurk91** [dustinspecker/eslint-config-angular#28]
Using [eslint-plugin-angular](https://github.com/Gillespie59/eslint-plugin-angular/releases/tag/1.0.0) v1.0.0 and eslint-config-angular v0.4.0.

It seems that these two rules 
- `angular/no-digest`
- `angular/typecheck-regexp`

No longer exists in eslint-plugin-angular.

**Comment by dustinspecker** [comment]
Thank you for reporting this! Should be fixed in `v0.5.0`.
