### ISSUE TITLE
Is it possible to turn off some of the rules

### ISSUE THREAD

**Issue by caglarcem** [dustinspecker/eslint-config-angular#46]
More like a question. I need to turn off some of the rules such as 'Controller naming' rule.

Is it possible to do this in a practical way, or how can I turn it off from "angular" rule set? Sorry if this is a very basic question, as I am relatively new to eslint.

**Comment by dustinspecker** [comment]
Yep, you can disable rules. In the `.eslintrc` file, do the following:

``` json
{
  "rules": {
    "angular/controller-name": 0
  }
}
```

This approach works for all rules provided by [eslint-plugin-angular](https://github.com/Gillespie59/eslint-plugin-angular).

Let me know if I can provide further help.
