### ISSUE TITLE
angular.isDefined(undefined)

### ISSUE THREAD

**Issue by Aprillion** [dustinspecker/eslint-config-angular#68]
I wanted to try this module, but when I ran eslint with `--fix` option, it completely broke some code.

e.g. `if ($scope.something.whatever == undefined)` => `if (angular.isDefined(undefined))`

So it's not trustworthy :(

**Comment by dustinspecker** [comment]
Thanks for reporting this issue! This repo is just a config file. The actual plugin is at https://github.com/Gillespie59/eslint-plugin-angular. Report this issue over there and I'm sure they can take a look at it.

**Comment by Aprillion** [comment]
I'm using eslint-plugin-angular with `extends: "plugin:angular/johnpapa"` without this issue.

It was only when I tried eslint-config-angular with `extends: "angular"` that I observed the problem.
